proxy_set_header Host               $host;
proxy_set_header X-Real-IP          $remote_addr;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-Host   $host;
proxy_set_header X-Forwarded-Port   $server_port;

proxy_http_version 1.1;
proxy_set_header Connection         "";

proxy_connect_timeout 60s;
proxy_send_timeout    300s;
proxy_read_timeout    300s;

proxy_buffering    on;
proxy_buffer_size  128k;
proxy_buffers      8 64k;
